name: rail_vacation_manager
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2
  path: ^1.9.0
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
